### ISSUE TITLE
Any support for ASP.NET Core MVC?

### ISSUE THREAD

**Issue by raylinder** [DotNet4Neo4j/Neo4j.AspNet.Identity#10]
Is there documentation to support ASP.NET Core MVC?

I've ripped out OrientDB from a pet project and now replacing it with Neo4j. I'm struggling to find any clear documentation to support ASP.NET Core MVC with ASP.NET Identity and Neo4j. This project seems to be the closest reference. So my question is, will the current documentation be replaced to support new ASP.NET Core MVC or will there be added documentation to support new ASP.NET Core MVC?

**Comment by cskardon** [comment]
Hey I just published a pre release of it, checkout Neo4j.AspNet.Identity.Core on nuget..

**Comment by cskardon** [comment]
It's also in my Github if you want to see the code

**Comment by raylinder** [comment]
Awesome! Thanks! I did create a custom implementation for this, however, I am curious about how you ported it.

**Comment by cskardon** [comment]
Sorry I would have done it earlier had I got a notice of your original
message, but for some reason I've not been getting notifications

**Comment by raylinder** [comment]
It's totally fine. I'm glad you are able to get it done so that others can enjoy the effects. We're all busy with life and to have something like this is greatly appreciated. Greatness takes time, as to the saying "Patience is a virtue". Keep up the great work!
