### ISSUE TITLE
Methods with NotImplementedException

### ISSUE THREAD

**Issue by StenPetrov** [DotNet4Neo4j/Neo4j.AspNet.Identity#8]
`UserStore<TUser>` class has methods that throw `NotImplementedException` and aren't virtual. I would be great if all methods in this class were virtual to allow for modifications to the storage mechanism as well as override the unimplemented methods.

**Comment by cskardon** [comment]
Hi, very quickly, please use the `Neo4jUserStore<TUser>` whilst still not 100% there, it's a lot more there than `UserStore<TUser>`.

Now, this doesn't solve your problem of virtual methods - I appreciate that :/

I'm not sure that it's a good idea to make all the methods virtual, my reasoning is that it'd be much better for you to do a pull request on the repo and add those methods in. If you really want to roll your own the best I could offer would be to write a wrapper class and chain your own implementations. 

I would definitely use the Neo4jUserStore though.
